CREATE TABLE SALARIES (
ID NUMBER(*,0) primary key not null, 
EMPLOYEE_ID NUMBER(*,0) not null, 
PROJECT_ID NUMBER(*,0), 
SALARY NUMBER(10,2) NOT NULL CHECK (SALARY >= 500)
);


CREATE TABLE PROJECTS (
ID NUMBER(*,0) primary key not null, 
CODE VARCHAR2(255 BYTE) NOT NULL, 
MANAGER_ID NUMBER(*,0), 
BUDGET NUMBER(10,2) NOT NULL,
DATE_OF_BEGENNING DATE,
DATE_OF_ENDING DATE
);


CREATE TABLE EMPLOYEES (
ID NUMBER(*,0) primary key not null, 
MANAGER_ID NUMBER(*,0), 
DATE_OF_JOINING DATE, 
FULL_NAME VARCHAR2(255 BYTE) NOT NULL
);


ALTER TABLE SALARIES ADD CONSTRAINT FK_SAlARY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (id);
ALTER TABLE SALARIES ADD CONSTRAINT FK_SAlARY_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (id);



ALTER TABLE PROJECTS ADD CONSTRAINT FK_MANAGER_PROJECT FOREIGN KEY(MANAGER_ID) REFERENCES EMPLOYEES (id);


ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_MANAGER  FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES (id);